### ISSUE TITLE
getImageSize has been fixed on Android?

### ISSUE THREAD

**Issue by winglight** [yoaicom/react-native-view-transformer#1]
The pixels prop is used to align the edge of the image content with the view's boundry and to determine the max scale.(We can actually use Image.getSize to get pixels info on iOS, but NOT on Android, so for now this prop is needed)
-I checked the link provided above and found someone advised to close the issue for solved this problem. Would you guys like to confirm if we don't need the prop "pixel" any more?

**Comment by ldn0x7dc** [comment]
@winglight Seems the related commit is in the master branch but not available in the latest release(v0.27.1) for now.

**Comment by winglight** [comment]
oic, i'm waiting...

**Comment by ldn0x7dc** [comment]
@winglight With RN 0.28, Image.getSize() is available on Android, and we have update our sources to use this feature. So the pixels prop is now optional for remote images.

**Comment by winglight** [comment]
@ldn0x7dc  Great job!

**Comment by ldn0x7dc** [comment]
We're considering moving **ViewTransformer.Image** to a dedicated module **[react-native-transformable-image](https://github.com/yoaicom/react-native-transformable-image)**.
This module will continue to serve as a more basic and general transform utility.
